### ISSUE TITLE
liquidd Segmentation fault

### ISSUE THREAD

**Issue by arowser** [Blockstream/liquid#1]
### Can you reliably reproduce the issue?

1.git clone and build liquid.3.14.1
2. run liquidd
3.  Segmentation fault

```
gdb liquidd
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from liquidd...done.
(gdb) r
Starting program: /data/other/liquid/src/liquidd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffedf0a700 (LWP 2539)]
[New Thread 0x7fffed709700 (LWP 2540)]
[New Thread 0x7fffecf08700 (LWP 2541)]
[New Thread 0x7fffdffff700 (LWP 2542)]
[New Thread 0x7fffdf7fe700 (LWP 2543)]
[New Thread 0x7fffdeffd700 (LWP 2544)]
[New Thread 0x7fffde7fc700 (LWP 2545)]
[New Thread 0x7fffddffb700 (LWP 2546)]
[New Thread 0x7fffdd7fa700 (LWP 2547)]
[New Thread 0x7fffdcff9700 (LWP 2548)]
[New Thread 0x7fffcffff700 (LWP 2549)]

Thread 1 "liquidd" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff70b2672 in __os_strdup () from /usr/lib/libdb_cxx-4.8.so
#2  0x00007ffff7085dc2 in __env_add_data_dir () from /usr/lib/libdb_cxx-4.8.so
#3  0x00007ffff7085e91 in __env_set_data_dir () from /usr/lib/libdb_cxx-4.8.so
#4  0x00007ffff6fa48e9 in DbEnv::set_data_dir(char const*) () from /usr/lib/libdb_cxx-4.8.so
#5  0x00005555557fb241 in CDBEnv::Open (this=0x555555d3f1c0 <bitdb>, pathIn=...) at wallet/db.cpp:89
#6  0x0000555555856e14 in CWallet::Verify () at wallet/wallet.cpp:551
#7  0x00005555555b49b5 in AppInitMain (threadGroup=..., scheduler=...) at init.cpp:1243
#8  0x0000555555594ec7 in AppInit (argc=<optimized out>, argv=<optimized out>) at bitcoind.cpp:167
#9  0x0000555555587d6f in main (argc=1, argv=0x7fffffffdd18) at bitcoind.cpp:196
(gdb) 
```

### What version of bitcoin-core are you using?
liquid.3.14.1

### Machine specs:
- OS: Ubuntu 18.04.1 LTS
- CPU:  i7-8700K
- RAM: 32G
- Disk size:
- Disk Type (HD/SDD):

**Comment by greenaddress** [comment]
Hello

Are you using the gitian or depends system to build the binary?

For example (using the depends system and assuming you got all the build tools installed):

```

git clone https://github.com/Blockstream/liquid.git
cd liquid/depends
make HOST=x86_64-pc-linux-gnu NO_QT=1
cd ..
./autogen.sh
./configure --prefix=$PWD/depends/x86_64-pc-linux-gnu   --disable-maintainer-mode --disable-dependency-tracking

make
make install
```

then in depends/x86_64-pc-linux-gnu you will find your binaries entirely built from sources (including boost, openssl, zeromq, etc)


If you aren't using the depends system but you are simply building dev (i.e. cd in repo, autogen, configure and make) then there may be some incompatibility between libraries. We plan to move to rebase to a later release soon, if this is fixed upstream we'll likely inherit it. In any case we'll look at the above and see if we can find a solution.

Other than the above is probably better if you try to do the gitian build or short of that directly the depends system (see example above) for more stable/reliable/tested builds.

**Comment by instagibbs** [comment]
Seems like a leveldb issue. Try the gitian builds as @greenaddress suggested.

**Comment by instagibbs** [comment]
possibly related: https://github.com/bitcoin/bitcoin/issues/12047

**Comment by arowser** [comment]
Its work fine after using the depends system, thanks.
